config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  root "home#index"

  resources :plumbers
  resources :events do 
    post :done

    collection do 
      get :certain_plumber_events
    end
  end
  resources :clients
end

app/models/client.rb
class Client < Base
  has_many :events, dependent: :destroy

  field :name, type: String
  field :age, type: Integer
  field :address, type: String
  field :private_note, type: String

  validates_presence_of :name, :age, :address
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.permit(:name, :age, :address, :private_note)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= form_for @client do |f|
  - if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |message|
          %li= message
  
  = label_tag "Name"
  = text_field_tag :name, ''
  %br
  = label_tag "Age"
  = number_field_tag :age, ''
  %br
  = label_tag "Address"
  = text_area_tag :address, ''
  %br
  = label_tag "Private note"
  = text_field_tag :private_note, ''

  .actions
    = f.submit 'Save'

app/views/clients/edit.html.haml
%h1 Editing client

= render 'form'

= link_to 'Show', @client
\|
= link_to 'Back', clients_path

app/views/clients/index.html.haml
%h1.caption 
  Listing clients
%table.table-latitude
  %thead
    %tr
      %th
        Name
      %th
        Age
      %th{width: '50%'}
        Address
      %th{width: '20%'}
        Actions

  %tbody
    - @clients.each do |client|
      %tr
        %td
          = client.name
        %td
          = client.age
        %td 
          = client.address
        %td
          .small-button
            = link_to 'Show', client
          .small-button
            = link_to 'Edit', edit_client_path(client)
          .small-button
            = link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }

- if current_admin
  %br
  = link_to 'New Client', new_client_path

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path

app/views/clients/show.html.haml
%p#notice= notice

= @client.name
%br
= @client.age
%br
= @client.address
%br
= @client.private_note

%br
= link_to 'Edit', edit_client_path(@client)
\|
= link_to 'Back', clients_path