config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  root "home#index"

  resources :plumbers
  resources :events do 
    post :done

    collection do 
      get :certain_plumber_events
    end
  end
  resources :clients
end

app/models/event.rb
class Event < Base
  belongs_to :client, dependent: :destroy
  has_and_belongs_to_many :plumbers

  as_enum :status, %i{pending done}, pluralize_scopes: false, field: { default: 0 }

  field :start_date, type: Date
  field :end_date, type: Date

  validates_presence_of :start_date, :end_date
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def done
    @event = Event.find(params[:event_id])
    @event.done!

    respond_to do |format|
      if @event.save
        format.html {redirect_to event_url(@event, notice: "Event was succesfully updated to Done statue.")}
        format.json {render :show, status: :updated, location: @event}
      else
        format.html {redirect_to events_url(notice: "Failed to update Event#{@event.id} status")}
        format.json {render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def certain_plumber_events
    @plumber = Plumber.find params[:plumber_id]
    @events = Event.where(plumber_ids: params[:plumber_id])

    if params[:start_date].present?
      @events = @events.where(:start_date.gte => params[:start_date])
    end

    if params[:end_date].present?
      @events = @events.where(:end_date.lte => params[:end_date])
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.permit(:client, :start_date, :end_date, :plumber_id, plumber_ids: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_certain_plumber_events_form.html.haml
= form_with :url => url_for(:controller => 'events', :action => 'certain_plumber_events'), method: :get do |f|
  = label_tag "Plumber"
  = select_tag :plumber_id, options_from_collection_for_select(Plumber.all, "id", "name")
  %br
  = label_tag "Event Period: "
  = label_tag "Start from"
  = date_field_tag :start_date, ""
  = label_tag "End at"
  = date_field_tag :end_date, ""

  .actions
    = f.submit 'Search'

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  = label_tag "Client"
  = select_tag :client, options_from_collection_for_select(Client.all, "id", "name")
  %br
  = label_tag "Plumbers"
  = select_tag :plumber_ids, options_for_select(Plumber.all.collect{|x| [x.name,x.id]}, @event.plumbers.pluck(:id)), multiple: true
  %br
  = label_tag "Event Period"
  %br
  = label_tag "Start from"
  = date_field_tag :start_date, @event.start_date
  %br
  = label_tag "End at"
  = date_field_tag :end_date, @event.end_date

  .actions
    = f.submit 'Save'

app/views/events/certain_plumber_events.html.haml
%h1.caption 
  = "Listing events for #{@plumber.name}"
%table.table-latitude
  %thead
    %tr
      %th
        Client Name
      %th
        Plumbers 
      %th
        Start Date
      %th
        End Date
      %th
        status

  %tbody
    - @events.each do |event|
      %tr
        %td
          = event.client.name
        %td
          = event.plumbers.map(&:name).join(",")
        %td 
          = event.start_date
        %td 
          = event.end_date
        %td
          = event.status

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1.caption 
  Listing events
%table.table-latitude
  %thead
    %tr
      %th
        Client Name
      %th
        Plumbers 
      %th
        Start Date
      %th
        End Date
      %th
        status
      %th
        Actions

  %tbody
    - @events.each do |event|
      %tr
        %td
          = event.client.name
        %td
          = event.plumbers.map(&:name).join(",")
        %td 
          = event.start_date
        %td 
          = event.end_date
        %td
          = event.status
        %td
          .small-button
            = link_to 'Show', event
          .small-button
            = link_to 'Edit', edit_event_path(event)
          .small-button
            = link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
          .small-button
            = button_to 'Done', event_done_path(event), method: :post

- if current_admin
  %br
  = link_to 'New Event', new_event_path

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

= "Client Name: #{@event.client.name}"
%br
= "Plumbers: #{@event.plumbers.map(&:name).join(",")}"
%br
= "Event Period: #{@event.start_date} to #{@event.end_date}"
%br
= "Event Status: #{@event.status}"
%br
= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path