config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  root "home#index"

  resources :plumbers
  resources :events do 
    post :done

    collection do 
      get :certain_plumber_events
    end
  end
  resources :clients
end

app/models/plumber.rb
class Plumber < Base
  has_and_belongs_to_many :event

  field :name, type: String
  field :address, type: String
  field :vehicles, type: Array, default: []

  validates_presence_of :name, :address
end

app/controllers/plumbers_controller.rb
class PlumbersController < ApplicationController
  before_action :set_plumber, only: %i[ show edit update destroy ]

  # GET /plumbers or /plumbers.json
  def index
    @plumbers = Plumber.all
  end

  # GET /plumbers/1 or /plumbers/1.json
  def show
  end

  # GET /plumbers/new
  def new
    @plumber = Plumber.new
  end

  # GET /plumbers/1/edit
  def edit
  end

  # POST /plumbers or /plumbers.json
  def create
    params = plumber_params
    vehicles = plumber_params[:vehicles]

    params[:vehicles] = vehicles.split(",").map do |v|
      v.strip
    end

    @plumber = Plumber.new(params)

    respond_to do |format|
      if @plumber.save
        format.html { redirect_to plumber_url(@plumber), notice: "Plumber was successfully created." }
        format.json { render :show, status: :created, location: @plumber }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plumber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plumbers/1 or /plumbers/1.json
  def update
    respond_to do |format|
      params = plumber_params
      vehicles = plumber_params[:vehicles]
  
      params[:vehicles] = vehicles.split(",").map do |v|
        v.strip
      end
      
      if @plumber.update(params)
        format.html { redirect_to plumber_url(@plumber), notice: "Plumber was successfully updated." }
        format.json { render :show, status: :ok, location: @plumber }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plumber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plumbers/1 or /plumbers/1.json
  def destroy
    @plumber.destroy

    respond_to do |format|
      format.html { redirect_to plumbers_url, notice: "Plumber was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plumber
      @plumber = Plumber.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plumber_params
      params.permit(:name, :address, :vehicles)
    end
end

app/helpers/plumbers_helper.rb
module PlumbersHelper
end

app/views/plumbers/_form.html.haml
= form_for @plumber do |f|
  - if @plumber.errors.any?
    #error_explanation
      %h2= "#{pluralize(@plumber.errors.count, "error")} prohibited this plumber from being saved:"
      %ul
        - @plumber.errors.full_messages.each do |message|
          %li= message

  = label_tag "Name"
  = text_field_tag :name, @plumber.name
  %br
  = label_tag "Address"
  = text_area_tag :address, @plumber.address
  %br
  = label_tag "Vehicles"
  = text_area_tag :vehicles, @plumber.vehicles.join(',')
  %br


  .actions
    = f.submit 'Save'

app/views/plumbers/edit.html.haml
%h1 Editing plumber

= render 'form'

= link_to 'Show', @plumber
\|
= link_to 'Back', plumbers_path

app/views/plumbers/index.html.haml
%h1.caption 
  Listing plumbers
%table.table-latitude
  %thead
    %tr
      %th
        Name
      %th
        Address 
      %th
        Vehicles
      %th 
        Actions

  %tbody
    - @plumbers.each do |plumber|
      %tr
        %td
          = plumber.name
        %td
          = plumber.address
        %td
          = plumber.vehicles.join(",")
        %td
          .small-button
            = link_to 'Show', plumber
          .small-button
            = link_to 'Edit', edit_plumber_path(plumber)
          .small-button
            = link_to 'Destroy', plumber, method: :delete, data: { confirm: 'Are you sure?' }

- if current_admin
  %br
  = link_to 'New Plumber', new_plumber_path

app/views/plumbers/new.html.haml
%h1 New plumber

= render 'form'

= link_to 'Back', plumbers_path

app/views/plumbers/show.html.haml
%p#notice= notice

= "Name: #{@plumber.name}"
%br
= "Address: #{@plumber.address}"
%br
= "Vehicles: #{@plumber.vehicles.join(',')}"
%br

= link_to 'Edit', edit_plumber_path(@plumber)
\|
= link_to 'Back', plumbers_path